excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Pods
  - Smilegate_Blog/AppDelegate.swift
  - Smilegate_Blog/SceneDelegate.swift
  - Smilegate_BlogTests/Smilegate_BlogTests.swift
  - Smilegate_BlogUITests/Smilegate_BlogUITests.swift
  - Smilegate_BlogUITests/Smilegate_BlogUITestsLaunchTests.swift

disabled_rules: # Default Rules에서 비활성화할 규칙
  - trailing_whitespace
  - force_cast
  - force_unwrapping
